---

sudo: false
language: python

install:
  - pip install tox-travis
script:
  - tox

matrix:
  include:
    - python: 3.7
    - python: 3.8
    - python: pypy3
    - python: 3.8
      env:
        - TOXENV=style
