---

sudo: false
language: python

install:
  - pip install tox-travis
script:
  - tox

matrix:
  include:
    - python: 3.6
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: pypy
    - python: pypy3
    - python: 3.6
      env:
        - TOXENV=style
